### ISSUE TITLE
configure fails when entering a single directory path in Google Drive path configuration

### ISSUE THREAD

**Issue by jacobmiller22** [jacobmiller22/chronolog#13]
See error details
```
1. google_drive
Valid choices are 1-1: 1
Enter the path to the Google Drive folder where the logs will be stored, including the name of the drive (My Drive, <shared_drive_name>, etc.) (default: My Drive/TEST/LOGS)
Enter a string: My Drive
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jacobmiller22/Projects/chronolog-test/venv/lib/python3.8/site-packages/chronolog/__main__.py", line 5, in <module>
    main()
  File "/home/jacobmiller22/Projects/chronolog-test/venv/lib/python3.8/site-packages/chronolog/cli.py", line 349, in main
    configure(args)
  File "/home/jacobmiller22/Projects/chronolog-test/venv/lib/python3.8/site-packages/chronolog/cli.py", line 324, in configure
    config[destination]["is_shared_drive"] = query_yes_no(
  File "/home/jacobmiller22/Projects/chronolog-test/venv/lib/python3.8/site-packages/chronolog/cli.py", line 84, in query_yes_no
    raise ValueError("invalid default answer: '%s'" % default)
ValueError: invalid default answer: 'False'
```

**Comment by jacobmiller22** [comment]
Resolved in PR #15
